name: 'code_functionality'
variables:
  enable_all: 'true'
jobs:
  - job: 'verify_deployment_provision'
    timeoutInMinutes: 20
    cancelTimeoutInMinutes: 12
    strategy:
      parallel: 1
    pool:
      vmImage: 'win1803'
    steps:
    - powershell: Install-Module -Name AzureRM -Scope CurrentUser -Force -SkipPublisherCheck -AllowClobber -MinimumVersion 6.10.3
    - powershell: Get-AzureRmSubscription